version: '3'
services:

  tg-bot:
    build: .
    ports:
      - "443:443"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes: 
      - "mongodb-data:/data/db"
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
    driver: local
    